name: Update README

on:
  schedule:
    - cron: "0 */12 * * *"   # обновление каждые 12 часов
  workflow_dispatch:          # можно запускать вручную

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Generate GitHub Stats
        uses: anuraghazra/github-readme-stats@master
        with:
          GITHUB_TOKEN: ${{ secrets.PAT }}
