name: Update README - Recent Projects

# Запускается по расписанию и вручную
on:
  schedule:
    - cron: "0 */12 * * *"   # каждые 12 часов (подстрой при желании)
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}   # чтобы action мог пушить изменения

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Generate recent repos markdown
        env:
          USERNAME: YOUR_GITHUB_USERNAME   # <-- замените на ваш GitHub username
          COUNT: 5                         # сколько репозиториев взять
        run: |
          echo "Fetching latest $COUNT repos for $USERNAME ..."
          API_URL="https://api.github.com/users/$USERNAME/repos?type=owner&sort=updated&per_page=$COUNT"
          curl -s -H "Authorization: token ${{ secrets.PAT }}" "$API_URL" > /tmp/repos.json

          # Собираем markdown со списком репо (имя — ссылка — краткое описание)
          echo "## 🚀 Recent Projects" > /tmp/recent.md
          echo "" >> /tmp/recent.md
          jq -r '.[] | "- [" + .name + "](" + .html_url + ") — " + (.description // "No description")' /tmp/repos.json >> /tmp/recent.md

          # Делаем безопасную замену между маркерами в README.md
          python3 - <<'PY'
import sys,io,re
with open('README.md','r',encoding='utf-8') as f:
    text=f.read()
start='<!--START_RECENT_REPOS-->'
end='<!--END_RECENT_REPOS-->'
if start in text and end in text:
    with open('/tmp/recent.md','r',encoding='utf-8') as r:
        new_block=r.read()
    new_text=re.sub(re.escape(start)+'.*?'+re.escape(end), start+'\n'+new_block+'\n'+end, text, flags=re.S)
    with open('README.md','w',encoding='utf-8') as f:
        f.write(new_text)
    print("README updated with recent projects.")
else:
    print("Markers not found in README.md. Please add <!--START_RECENT_REPOS--> and <!--END_RECENT_REPOS--> where needed.")
PY

      - name: Commit and push changes
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --staged --quiet || (git commit -m "chore: update README with recent projects" && git push)
